SuperShopManagementSystem/Models/ItemCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SuperShopManagementSystem.Models
{
    public class ItemCategory
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is Required")]
        [StringLength(maximumLength: 50, ErrorMessage = "Chategory Name Should be in Between 2 and 50 Characters",MinimumLength =2)]
        public string Name { get; set; }


        [Required(ErrorMessage = "Code is Required")]
        public string Code { get; set; }

        [DataType(DataType.MultilineText)]
        [StringLength(maximumLength:100,ErrorMessage ="Maximum 100 Chararcters are Allowed")]
        public string Description { get; set; }


        public byte[] Image { get; set; }
        
        public bool IsDeleted { get; set; }


        [Display(Name = "Parent Category")]
        public Nullable<int> ParentId { get; set; }
        public virtual ItemCategory Parent { get; set; }

        public virtual List<ItemCategory> ItemCategories { get; set; }

        public virtual List<Item> Items { get; set; }
    }
}

SuperShopManagementSystem/Controllers/ItemCategoriesController.cs
using SuperShopManagementSystem.BLL;
using SuperShopManagementSystem.Models;
using SuperShopManagementSystem.Models.DatabaseContex;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace SuperShopManagementSystem.Controllers
{
    public class ItemCategoriesController : Controller
    {
        ItemCategoryBLL itemCategoryBll = new ItemCategoryBLL();
        DropDownBLL dropDownBll = new DropDownBLL(); 
        bool status = false;
        Common common = new Common();

        // Create Item Category [Get Request]
        public ActionResult Create()
        {
            return View();
        }


        // Create Item Category [Post Request]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemCategory itemCategory,HttpPostedFileBase ImageFile)
        {
            if (ImageFile == null)
            {
                ModelState.AddModelError("Image", "Please Upload an Image");
            }


            bool isValidFormat = itemCategoryBll.CheckImageFormat(ImageFile);
            if (isValidFormat == false)
            {
                ModelState.AddModelError("Image", "Only jpg , png , jpeg are allowed");
            }

            itemCategory.IsDeleted = false;

            if (ModelState.IsValid)
            {
                
                status = itemCategoryBll.Create(itemCategory, ImageFile);
                if (status == true)
                {

                    ViewBag.Msg = "Item Category Successfully Added";
                    ModelState.Clear();
                    return View();
                }
                if (status == true)
                {

                    ViewBag.Msg = "Item Category Added Failed";
                }

            }
            
            return View(itemCategory);
        }



        //Update Item Category [Get Request]
        public ActionResult Update(int ?id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            ItemCategory itemCategory = itemCategoryBll.GetById(id);

            if (itemCategory == null)
            {
                return RedirectToAction("Error", "Home", null);
            }

            ViewBag.ParentId = dropDownBll.GetParentParentById(id);
            return View(itemCategory);
        }



        //Update Item Category [Post Request]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ItemCategory itemCategory, HttpPostedFileBase ImageFile, byte[] CurrentImage)
        {
            if (ImageFile == null)
            {

                itemCategory.Image = CurrentImage;
            }

            if (ImageFile != null)
            {
                bool isValidFormat = common.CheckImageFormat(ImageFile);
                if (isValidFormat == false)
                {
                    itemCategory.Image = CurrentImage;
                    ModelState.AddModelError("Image", "Only jpg , png , jpeg are allowed");
                }
                else
                {
                    itemCategory.Image = common.ConvertImage(ImageFile);
                }

            }
            if (ModelState.IsValid)
            {
                status = itemCategoryBll.Update(itemCategory);
                if (status == true)
                {
                    return RedirectToAction("ShowAll");
                }
            }

            ViewBag.ParentId = dropDownBll.GetParentParentById(itemCategory.Id);
            return View();
        }



        [HttpPost]
        //Delete Item Category [Post Request]
        public JsonResult Delete(int id)
        {
            status = itemCategoryBll.Delete(id);
            if (status)
            {
                return Json(1);
            }
            return Json(0);
        }



        //Get All Category Item
        public ActionResult ShowAll()
        {

            List<ItemCategory> listOfItemCategory = itemCategoryBll.GetAll();
            //db.Configuration.ProxyCreationEnabled = false;
            //var jsonDataList = listOfItemCategory.Select(model => new { Name = model.Name, Code = model.Code, Description = model.Description, PCategory=model.Parent.Name });
            //JavaScriptSerializer javaScriptSerializer = new JavaScriptSerializer();
            //javaScriptSerializer.MaxJsonLength = Int32.MaxValue;
            //string jsonData = javaScriptSerializer.Serialize(jsonDataList);
            //return Json(jsonData, JsonRequestBehavior.AllowGet);
            return View(listOfItemCategory);
        }


        //Get All Parent Category
        public JsonResult GetParentCategories()
        {
            //db.Configuration.ProxyCreationEnabled = false;
            var listOfItemCategory = itemCategoryBll.GetParentCategories();
            var jsonData = listOfItemCategory.Select(model => new { Id = model.Id, Name = model.Name });
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }


        //Generating Random Category Code
        public JsonResult GetCategoryCode()
        {
            string categoryCode=itemCategoryBll.GetCategoryCode();
            return Json(categoryCode);
        }


        //Checking Category Name Availability
        public JsonResult CheckCategoryName(string data)
        {
             status =itemCategoryBll.CheckCategoryName(data);
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);


        }
    }


}

SuperShopManagementSystem/Views/ItemCategories/Create.cshtml
@model SuperShopManagementSystem.Models.ItemCategory

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="text-center">Add Item Category</h4>
            </div>
            <div class="panel-body">
                <div class="row">

                    <div class="col-md-6 col-md-offset-3">
                        @using (Html.BeginForm("Create", "ItemCategories", FormMethod.Post, new { enctype = "multipart/form-data",id="form" }))
                        {

                        
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @if (ViewBag.Msg != null)
                                {
                                     <div style="border:1px solid #e6dbdb;padding:5px;background-color:#f5f5f5;color:green;font-weight:bold;border-radius:5px" class="text-center col-md-offset-3">@ViewBag.Msg</div>
                                     <br />
                                }
                               

                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    <div class="col-md-4 col-md-offset-3">
                                        @Html.RadioButton("Category", "RootCategory", true) Root Category
                                    </div>
                                    <div class="col-md-4">
                                        @Html.RadioButton("Category", "ChildCategory") Child Category
                                    </div>
                                </div>
                                <div class="form-group " id="ParentCategoryDiv">
                                    @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(model => model.ParentId, new SelectList(""), "---Select Option---", new { @class = "form-control" })

                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    <div class="text-danger" id="ErrorMsg"></div>
                                    </div>

                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        <input type="file" name="ImageFile" id="Image" />
                                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                                        <br>
                                        <div class="col-md-6">
                                            <div id="imagePreview" style="display:none">
                                                <div class="thumbnail">
                                                    <img class="img-responsive" id="TargetImage" />
                                                </div>
                                            </div>

                                            <div class="">
                                                <p id="Imagedescription"></p>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" id="btnSubmit" value="Create" class="btn btn-block btn-success btn-lg" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/ProjectScript/ItemCategory/ItemCategory_Create.js"></script>

}

SuperShopManagementSystem/Views/ItemCategories/ShowAll.cshtml
@model IEnumerable<SuperShopManagementSystem.Models.ItemCategory>

@{
    ViewBag.Title = "ShowAll";
}


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="text-center">All The Item Category</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-bordered table-condensed table-striped table-responsive  search-table">

                            <thead>
                                <tr>

                                    <th>
                                        Category
                                    </th>

                                    <th>
                                        Code
                                    </th>
                                    <th>
                                        Parent Category
                                    </th>
                                    <th>
                                        Description
                                    </th>
                                    <th>
                                        Image
                                    </th>
                                    <th>
                                        Action
                                    </th>
                                </tr>
                            </thead>


                            <tbody>

                                @foreach (var item in Model)
            {
                    <tr id="DelRow_@item.Id">

                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Code)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Parent.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            @{
            string imageBase64 = Convert.ToBase64String(item.Image);
            string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                            }
                            <img src="@imageSrc" width="100" height="100" />
                        </td>
                        <td>
                            @Html.ActionLink("Update", "Update", new { id = item.Id },new {@class="btn btn-primary" })
                            <!-- Trigger the modal with a button -->
                            <a href="#" class="btn btn-danger" onclick="GetDeleteId(@item.Id)">Delete</a>
                        </td>
                    </tr>
}
                            </tbody>
                        </table>

                        @Html.Hidden("DeleteId")

                        <!-- Modal -->
                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">

                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>

                                        <h2 class="modal-title">Confirm to Delete Item Category</h2>
                                    </div>
                                    <div class="modal-body">
                                        <h4>Are you sure to Delete this Item Category ???</h4>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                        <input type="button" class="btn btn-danger" value="Confirm Delete" id="btnConfirmDelete" />
                                    </div>
                                </div>

                            </div>
                        </div>


                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script>
         var GetDeleteId = function (Id) {
             $("#DeleteId").val(Id);
             $("#myModal").modal("show");
         }

         $("#btnConfirmDelete").on("click", function () {
             var deleteId = $("#DeleteId").val();
             $.ajax({
                 url: "/ItemCategories/Delete",
                 data: { id: deleteId },
                 method: "post",
                 success: function (response) {
                     if (response == 1) {
                         $("#myModal").modal("hide");
                         $("#DelRow_" + deleteId).remove();
                     }
                 }
             })
         })

    </script>
}

SuperShopManagementSystem/Views/ItemCategories/Update.cshtml
@model SuperShopManagementSystem.Models.ItemCategory

@{
    ViewBag.Title = "Update";
}


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="text-center">Update Item Category</h4>
            </div>
            <div class="panel-body">
                <div class="row">

                    <div class="col-md-6 col-md-offset-3">
                        @using (Html.BeginForm("Update", "ItemCategories", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
                        {


                            @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @if (ViewBag.Msg != null)
    {
                        <div style="border:1px solid #e6dbdb;padding:5px;background-color:#f5f5f5;color:green;font-weight:bold;border-radius:5px" class="text-center col-md-offset-3">@ViewBag.Msg</div>
                        <br />
}


                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group " id="ParentCategoryDiv">
                                @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.DropDownListFor(model => model.ParentId, null, "---No Parent Category---", new { @class = "form-control" })

                                </div>
                            </div>
                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    <div class="text-danger" id="ErrorMsg"></div>
                                </div>

                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                                    @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-3" })
                                <div class="col-md-9">
                                    <input type="file" name="ImageFile" id="Image" />
                                    @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                                    <br>
                                    <div class="col-md-6" id="CurrentImage">
                                        @{
                    string imageBase64 = Convert.ToBase64String(Model.Image);
                    string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                                        }
                                        <img src="@imageSrc" width="150" height="150" class="thumbnail" />
                                    </div>
                                    <div class="col-md-6" id="NewImage">
                                        <div id="imagePreview" style="display:none">
                                            <div class="thumbnail">
                                                <img class="img-responsive" id="TargetImage" />
                                            </div>
                                        </div>

                                        <div class="">
                                            <p id="Imagedescription"></p>
                                        </div>
                                    </div>

                                </div>

                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-3 col-md-9">
                                    <input type="submit" id="btnSubmit" value="Update" class="btn btn-block btn-success btn-lg" />
                                </div>
                            </div>
                            @Html.Hidden("CurrentCategoryName", Model.Name)
                            @Html.HiddenFor(model => model.IsDeleted)
                            @Html.Hidden("CurrentImage", Model.Image)
                        </div>
                        }
                    </div>

                </div>
            </div>

        </div>
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/ProjectScript/ItemCategory/ItemCategories_Update.js"></script>
}