SuperShopManagementSystem/Models/Party.cs
using SuperShopManagementSystem.Models.Operation;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SuperShopManagementSystem.Models
{
    public class Party
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is Required")]
        [StringLength(maximumLength: 50, ErrorMessage = "Name Should be in Between 2 and 50 Characters", MinimumLength = 2)]
        public string Name { get; set; }

        [Required(ErrorMessage ="Contact Number is Required")]
        [DataType(DataType.PhoneNumber)]
        public string ContactNo { get; set; }

        public byte[] Image { get; set; }

        [Required(ErrorMessage = "Code is Required")]
        public string Code { get; set; }

        [Required(ErrorMessage ="Email is Required")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [StringLength(maximumLength: 500, ErrorMessage = "Maximum 500 Characters are Allowed")]
        [DataType(DataType.MultilineText)]
        public string Address { get; set; }
        
        [Required(ErrorMessage ="Party type is required")]
        public string Type { get; set; }

        [Required]
        public bool IsDeleted { get; set; }

        public virtual List<Purchase> Purchases { get; set; }

    }
}

SuperShopManagementSystem/Controllers/PartiesController.cs
using SuperShopManagementSystem.BLL;
using SuperShopManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperShopManagementSystem.Controllers
{
    public class PartiesController : Controller
    {
        PartyBLL partyBll = new PartyBLL();
        Common common = new Common();
        DropDownList dropDown = new DropDownList();
        bool status = false;

        //GET: Create Party 
        public ActionResult Create()
        {
            return View();
        }


        //POST: Create Party
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Party party, HttpPostedFileBase ImageFile)
        {
            if (ImageFile == null)
            {
                ModelState.AddModelError("Image", "Please Upload an Image");
            }

            if (ImageFile != null)
            {
                bool isValidFormat = common.CheckImageFormat(ImageFile);
                if (isValidFormat == false)
                {
                    ModelState.AddModelError("Image", "Only jpg , png , jpeg are allowed");
                }
                else
                {
                    byte[] convertedImage = common.ConvertImage(ImageFile);
                    party.Image = convertedImage;
                }


            }
            party.IsDeleted = false;

            if (ModelState.IsValid)
            {

                status = partyBll.Create(party);
                if (status == true)
                {

                    ViewBag.Msg = "Party Successfully Added";
                    ModelState.Clear();
                    return View();
                }
                if (status == false)
                {

                    ViewBag.Msg = "Party Added Failed !";
                }

            }
            return View(party);
        }



        //Update Party  [Get Request]
        public ActionResult Update(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            Party party = partyBll.GetById(id);

            if (party == null)
            {
                return RedirectToAction("Error", "Home", null);
            }

            return View(party);
        }



        //Update Party Category [Post Request]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(Party party, HttpPostedFileBase ImageFile, byte[] CurrentImage)
        {

            if (ImageFile == null)
            {

                party.Image = CurrentImage;
            }

            if (ImageFile != null)
            {
                bool isValidFormat = common.CheckImageFormat(ImageFile);
                if (isValidFormat == false)
                {
                    party.Image = CurrentImage;
                    ModelState.AddModelError("Image", "Only jpg , png , jpeg are allowed");
                }
                else
                {
                    party.Image = common.ConvertImage(ImageFile);
                }

            }

            if (ModelState.IsValid)
            {

                status = partyBll.Update(party);
                if (status == true)
                {
                    return RedirectToAction("ShowAll");
                }
                if (status == false)
                {

                    ViewBag.Msg = "Party Category Added Failed !";
                }

            }
            return View(party);
        }



        [HttpPost]
        //Delete Party [Post Request]
        public JsonResult Delete(int id)
        {
            status = partyBll.Delete(id);
            if (status)
            {
                return Json(1);
            }
            return Json(0);
        }



        //Show All Party
        public ActionResult ShowAll()
        {

            List<Party> listOfParty = partyBll.GetAll();
            return View(listOfParty);
        }


        //Show Party Detail
        public ActionResult Details(int? id)
        {
            Party party = partyBll.GetById(id);
            return PartialView("Details_Partial", party);
        }


        //Generating Random Category Code
        public JsonResult GetPartyCode()
        {
            string partyCode = partyBll.GetPartyCode();
            return Json(partyCode);
        }


        //Checking Party Email Availability
        public JsonResult CheckPartyEmail(string email,string type)
        {
            status = partyBll.CheckPartyEmail(email,type);
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);
        }
    }
}

SuperShopManagementSystem/Views/Parties/Create.cshtml
@model SuperShopManagementSystem.Models.Party

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="text-center">Add A Party</h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        @using (Html.BeginForm("Create", "Parties", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @if (ViewBag.Msg != null)
                                {
                                    <div class="text-center col-md-offset-3 SuccessMsg">@ViewBag.Msg</div>
                                    <br />
                                }
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        <div class="form-group" style="margin-top:6px">
                                            <div class="col-md-4">
                                                @Html.RadioButtonFor(model => model.Type, "Customer",new {@checked=true }) Customer
                                            </div>
                                            <div class="col-md-4">
                                                @Html.RadioButtonFor(model => model.Type, "Supplier") Supplier
                                            </div>
                                        </div>
                                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        <div class="text-danger" id="ErrorMsg"></div>
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        <input type="file" name="ImageFile" id="Image" />
                                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                                        <br>
                                        <div class="col-md-6">
                                            <div id="imagePreview" style="display:none">
                                                <div class="thumbnail">
                                                    <img class="img-responsive" id="TargetImage" />
                                                </div>
                                            </div>

                                            <div class="">
                                                <p id="Imagedescription"></p>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Create" class="btn btn-block btn-success btn-lg" />
                                    </div>
                                </div>
                            </div>
                        }
                        <div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="~/Scripts/ProjectScript/Party/Create_Party.js"></script>

}

SuperShopManagementSystem/Views/Parties/Details_Partial.cshtml
@model SuperShopManagementSystem.Models.Party

<div class="col-md-3">
    @{
        string imageBase64 = Convert.ToBase64String(Model.Image);
        string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
    }
    <img src="@imageSrc" width="270" height="230" class="Thumbnail" />
</div>
<div class="col-md-8 col-md-offset-1">
    <dl class="dl-horizontal" style="font-size:18px">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ContactNo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ContactNo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

    </dl>
</div>

SuperShopManagementSystem/Views/Parties/ShowAll.cshtml
@model IEnumerable<SuperShopManagementSystem.Models.Party>

@{
    ViewBag.Title = "ShowAll";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="text-center">All Party List</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-bordered table-condensed table-striped table-responsive search-table ">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Name)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.ContactNo)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Image)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Code)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Type)
                                    </th>
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                <tr id="DelRow_@item.Id">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.ContactNo)
                                    </td>
                                    <td>
                                        @{
            string imageBase64 = Convert.ToBase64String(item.Image);
            string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                                        }
                                        <img src="@imageSrc" width="50" height="50" />
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Code)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Email)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Type)
                                    </td>
                                    <td>
                                        @Html.ActionLink("Update", "Update", new { id = item.Id }, new { @class = "btn btn-primary" })
                                        <a href="#" class="btn btn-info" onclick="Details(@item.Id)">Details</a>
                                        <a href="#" class="btn btn-danger" onclick="GetDeleteId(@item.Id)">Delete</a>
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>

                        @Html.Hidden("DeleteId")

                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                Modal content
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>

                                        <h2 class="modal-title">Confirm to Delete Party</h2>
                                    </div>
                                    <div class="modal-body">
                                        <h4>Are you sure to Delete this Party ???</h4>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                        <input type="button" class="btn btn-danger" value="Confirm Delete" id="btnConfirmDelete" />
                                    </div>
                                </div>

                            </div>
                        </div>


                        <div id="DetailsModal" class="modal fade" role="dialog">
                            <div class="modal-dialog modal-lg">

                                <!-- Modal content-->
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>

                                        <h2 class="modal-title">Party Details</h2>
                                    </div>
                                    <div class="modal-body" id="DetailsBody">
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                    </div>
                                </div>

                            </div>
                        </div>


                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts {

    <script src="~/Scripts/ProjectScript/Party/ShowAll_Party.js"></script>
}

SuperShopManagementSystem/Views/Parties/Update.cshtml
@model SuperShopManagementSystem.Models.Party

@{
    ViewBag.Title = "Update";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h4 class="text-center">Update A Party</h4>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-6 col-md-offset-3">
                        @using (Html.BeginForm("Update", "Parties", FormMethod.Post, new { enctype = "multipart/form-data", id = "form" }))
                        {
                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @if (ViewBag.Msg != null)
                                {
                                    <div class="text-center col-md-offset-3 SuccessMsg">@ViewBag.Msg</div>
                                    <br />
                                }
                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })

                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Type, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        <div class="form-group" style="margin-top:6px">
                                            <div class="col-md-4">
                                                @Html.RadioButtonFor(model => model.Type, "Customer", new { @checked = true }) Customer
                                            </div>
                                            <div class="col-md-4">
                                                @Html.RadioButtonFor(model => model.Type, "Supplier") Supplier
                                            </div>
                                        </div>
                                        @Html.ValidationMessageFor(model => model.Type, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                        <div class="text-danger" id="ErrorMsg"></div>
                                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.ContactNo, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.ContactNo, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.ContactNo, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        <input type="file" name="ImageFile" id="Image" />
                                        @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
                                        <br>
                                        <div class="col-md-6" id="CurrentImage">
                                            @{
                                                string imageBase64 = Convert.ToBase64String(Model.Image);
                                                string imageSrc = string.Format("data:image/gif;base64,{0}", imageBase64);
                                            }
                                            <img src="@imageSrc" width="150" height="150" class="thumbnail" />
                                        </div>
                                        <div class="col-md-6" id="NewImage">
                                            <div id="imagePreview" style="display:none">
                                                <div class="thumbnail">
                                                    <img class="img-responsive" id="TargetImage" />
                                                </div>
                                            </div>

                                            <div class="">
                                                <p id="Imagedescription"></p>
                                            </div>
                                        </div>

                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" value="Update" class="btn btn-block btn-success btn-lg" />
                                    </div>
                                </div>
                                @Html.Hidden("CurrentEmail", Model.Email)
                                @Html.Hidden("CurrentType", Model.Type)
                                @Html.HiddenFor(model => model.IsDeleted)
                                @Html.Hidden("CurrentImage", Model.Image)
                            </div>
                        }
                        <div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
<script src="~/Scripts/ProjectScript/Party/Update_Party.js"></script>
}