SuperShopManagementSystem/Models/ExpenseCategory.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SuperShopManagementSystem.Models
{
    public class ExpenseCategory
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage = "Name is Required")]
        [StringLength(maximumLength: 50, ErrorMessage = "Chategory Name Should be in Between 2 and 50 Characters", MinimumLength = 2)]
        public string Name { get; set; }


        [Required(ErrorMessage = "Code is Required")]
        public string Code { get; set; }

        [DataType(DataType.MultilineText)]
        [StringLength(maximumLength: 100, ErrorMessage = "Maximum 100 Chararcters are Allowed")]
        public string Description { get; set; }

        public bool IsDeleted { get; set; }


        [Display(Name = "Parent Category")]
        public Nullable<int> ParentId { get; set; }
        public virtual ExpenseCategory Parent { get; set; }

        public virtual List<ExpenseCategory> ExpenseCategories { get; set; }

        public virtual List<ExpenseItem> ExpenseItems { get; set; }
    }
}

SuperShopManagementSystem/Controllers/ExpenseCategoriesController.cs
using SuperShopManagementSystem.BLL;
using SuperShopManagementSystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperShopManagementSystem.Controllers
{
    public class ExpenseCategoriesController : Controller
    {
        ExpenseCategoryBLL expenseCategoryBll = new ExpenseCategoryBLL();
        DropDownBLL dropDownBll = new DropDownBLL();
        bool status = false;
        Common common = new Common();

        //GET: Create Expense Category
        public ActionResult Create()
        {
            return View();
        }


        // POST: Create Expense Category
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ExpenseCategory expenseCategory)
        {

            expenseCategory.IsDeleted = false;

            if (ModelState.IsValid)
            {

                status = expenseCategoryBll.Create(expenseCategory);
                if (status == true)
                {

                    ViewBag.Msg = "Expense Category Successfully Added";
                    ModelState.Clear();
                    return View();
                }
                if (status == true)
                {

                    ViewBag.Msg = "Expense Category Added Failed";
                }

            }

            return View(expenseCategory);
        }

        //Update Item Category [Get Request]
        public ActionResult Update(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }

            ExpenseCategory expenseCategory = expenseCategoryBll.GetById(id);

            if (expenseCategory == null)
            {
                return RedirectToAction("Error", "Home", null);
            }

            ViewBag.ParentId = dropDownBll.GetExpenseParentById(id);
            return View(expenseCategory);
        }



        //Update Item Category [Post Request]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Update(ExpenseCategory ExpenseCategory)
        {
            if (ModelState.IsValid)
            {
                status = expenseCategoryBll.Update(ExpenseCategory);
                if (status)
                {
                    return RedirectToAction("ShowAll");
                }
            }

            ViewBag.ParentId = dropDownBll.GetExpenseParentById(ExpenseCategory.Id);
            return View(ExpenseCategory);
            
        }



        [HttpPost]
        //Delete Item Category [Post Request]
        public JsonResult Delete(int id)
        {
            status = expenseCategoryBll.Delete(id);
            if (status)
            {
                return Json(1);
            }
            return Json(0);
        }



        //Show All Expense Category
        public ActionResult ShowAll()
        {

            List<ExpenseCategory> listOfExpenseCategory = expenseCategoryBll.GetAll();
            return View(listOfExpenseCategory);
        }


        //Get All Parent Category
        public JsonResult GetParentCategories()
        {
            //db.Configuration.ProxyCreationEnabled = false;
            var listOfExpenseCategory = expenseCategoryBll.GetParentCategories();
            var jsonData = listOfExpenseCategory.Select(model => new { Id = model.Id, Name = model.Name });
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }


        //Generating Random Category Code
        public JsonResult GetCategoryCode()
        {
            string categoryCode = expenseCategoryBll.GetCategoryCode();
            return Json(categoryCode);
        }


        //Checking Category Name Availability
        public JsonResult CheckCategoryName(string data)
        {
            status = expenseCategoryBll.CheckCategoryName(data);
            if (status == true)
            {
                return Json(1);
            }
            return Json(0);


        }
    }
}

SuperShopManagementSystem/Views/ExpenseCategories/Create.cshtml
@model SuperShopManagementSystem.Models.ExpenseCategory

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="text-center">Add Expense Category</h4>
            </div>
            <div class="panel-body">
                <div class="row">

                    <div class="col-md-6 col-md-offset-3">
                        @using (Html.BeginForm("Create", "ExpenseCategories", FormMethod.Post,new {id="ExpenseCategoryForm" }))
                        {


                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @if (ViewBag.Msg != null)
                                {
                                    <div style="border:1px solid #e6dbdb;padding:5px;background-color:#f5f5f5;color:green;font-weight:bold;border-radius:5px" class="text-center col-md-offset-3">@ViewBag.Msg</div>
                                    <br />
                                }


                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group">
                                    <div class="col-md-4 col-md-offset-3">
                                        @Html.RadioButton("Category", "RootCategory", true) Root Category
                                    </div>
                                    <div class="col-md-4">
                                        @Html.RadioButton("Category", "ChildCategory") Child Category
                                    </div>
                                </div>
                                <div class="form-group " id="ParentCategoryDiv">
                                    @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(model => model.ParentId, new SelectList(""), "---Select Option---", new { @class = "form-control" })

                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                        <div class="text-danger" id="ErrorMsg"></div>
                                    </div>

                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" id="btnSubmit" value="Create" class="btn btn-block btn-success btn-lg" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

    <script src="~/Scripts/ProjectScript/ExpenseCategory/Create_ExpenseCategory.js"></script>

}

SuperShopManagementSystem/Views/ExpenseCategories/ShowAll.cshtml
@model IEnumerable<SuperShopManagementSystem.Models.ExpenseCategory>

@{
    ViewBag.Title = "ShowAll";
}

<table class="table table-bordered table-condensed table-striped table-responsive  search-table">

    <thead>
        <tr>

            <th>
                Category Name
            </th>

            <th>
                Code
            </th>
            <th>
                Parent Category
            </th>
            <th>
                Description
            </th>
            <th>
                Action
            </th>
        </tr>
    </thead>


    <tbody>

        @foreach (var item in Model)
        {
            <tr id="DelRow_@item.Id">

                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Code)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Parent.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.ActionLink("Update", "Update", new { id = item.Id },new { @class = "btn btn-primary" })
                    <!-- Trigger the modal with a button -->
                    <a href="#" class="btn btn-danger" onclick="GetDeleteId(@item.Id)">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@Html.Hidden("DeleteId")

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>

                <h2 class="modal-title">Confirm to Delete Expense Category</h2>
            </div>
            <div class="modal-body">
                <h4>Are you sure to Delete this Expense Category ???</h4>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                <input type="button" class="btn btn-danger" value="Confirm Delete" id="btnConfirmDelete" />
            </div>
        </div>

    </div>
</div>



@section Scripts {

    <script>
         var GetDeleteId = function (Id) {
             $("#DeleteId").val(Id);
             $("#myModal").modal("show");
         }

         $("#btnConfirmDelete").on("click", function () {
             var deleteId = $("#DeleteId").val();
             $.ajax({
                 url: "/ExpenseCategories/Delete",
                 data: { id: deleteId },
                 method: "post",
                 success: function (response) {
                     if (response == 1) {
                         $("#myModal").modal("hide");
                         $("#DelRow_" + deleteId).remove();
                     }
                 }
             })
         })

    </script>
}

SuperShopManagementSystem/Views/ExpenseCategories/Update.cshtml
@model SuperShopManagementSystem.Models.ExpenseCategory

@{
    ViewBag.Title = "Update";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="text-center">Update Expense Category</h4>
            </div>
            <div class="panel-body">
                <div class="row">

                    <div class="col-md-6 col-md-offset-3">
                        @using (Html.BeginForm("Update", "ExpenseCategories", FormMethod.Post, new { id = "ExpenseCategoryForm" }))
                        {


                            @Html.AntiForgeryToken()

                            <div class="form-horizontal">
                                @if (ViewBag.Msg != null)
                                {
                                    <div style="border:1px solid #e6dbdb;padding:5px;background-color:#f5f5f5;color:green;font-weight:bold;border-radius:5px" class="text-center col-md-offset-3">@ViewBag.Msg</div>
                                    <br />
                                }


                                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                                <div class="form-group " id="ParentCategoryDiv">
                                    @Html.LabelFor(model => model.ParentId, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.DropDownListFor(model => model.ParentId, null, "---No Parent Category---", new { @class = "form-control" })

                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                        <div class="text-danger" id="ErrorMsg"></div>
                                    </div>

                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Code, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Code, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                                        @Html.ValidationMessageFor(model => model.Code, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-3" })
                                    <div class="col-md-9">
                                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-offset-3 col-md-9">
                                        <input type="submit" id="btnSubmit" value="Update" class="btn btn-block btn-success btn-lg" />
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>


@section Scripts {
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

}