SuperShopManagementSystem/Controllers/ExpensesController.cs
using SuperShopManagementSystem.BLL;
using SuperShopManagementSystem.Models;
using SuperShopManagementSystem.Models.Operation;
using SuperShopManagementSystem.Models.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SuperShopManagementSystem.Controllers
{
    public class ExpensesController : Controller
    {
        Common common = new Common();
        DropDownList dropdown = new DropDownList();
        ExpenseBLL expenseBll = new ExpenseBLL();
        bool status = false;
        // GET:Create Expense
        public ActionResult Create()
        {
            ViewBag.EmployeeId = dropdown.GetAllEmployee();
            ViewBag.OutletId = dropdown.GetAllOutlet();
            ViewBag.ItemId = dropdown.GetAllExpenseItem();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        // Post:Create Expenses
        public ActionResult Create(Expense expense)
        {
            if (ModelState.IsValid && expense.ExpenseDetails != null && expense.ExpenseDetails.Count > 0)
            {
                expense.IsDeleted = false;
                status = expenseBll.Create(expense);
                if (status == true)
                {
                    ViewBag.SuccessMsg = "Expense Item Successfully";
                    ModelState.Clear();
                }
            }

            ViewBag.ItemId = dropdown.GetAllItem();
            ViewBag.OutletId = dropdown.GetAllOutlet();
            ViewBag.EmployeeId = dropdown.GetAllEmployee();
            ViewBag.PartyId = dropdown.GetAllSupplier();
            return View();
        }

        //Expense Result
        public ActionResult ExpenseResult(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            ExpenseResultVM expenseResultVM = expenseBll.GetExpenseDetail(id);
            if (expenseResultVM == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return View(expenseResultVM);
        }

        //Details of Expense
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            ExpenseResultVM expenseResultVM = expenseBll.GetExpenseDetail(id);
            return View(expenseResultVM);
        }


        //Show All Expenses
        public ActionResult ShowAll()
        {
            List<Expense> expense = expenseBll.GetAll();
            return View(expense);
        }


        //Convert to PDF
        public ActionResult ExpenseReceiptPdf(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Error", "Home");
            }
            return new Rotativa.ActionAsPdf("ExpenseResult", new { id = id });
        }
    }
}

SuperShopManagementSystem/Views/Expenses/Create.cshtml
@model SuperShopManagementSystem.Models.Operation.Expense

@{
    ViewBag.Title = "Create";
}


<div class="panel panel-primary">
    <div class="panel-heading">
        Add Expense
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-md-3">
                <div class="form-group">
                    @Html.Label("Item")
                    @Html.DropDownList("ItemId", ViewBag.ItemId as SelectList, "---Select One---", new { @class = "form-control" })
                    <div id="ErrorMsgForItem" style="color:red"></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">

                    @Html.Label("Quantity")
                    @Html.TextBox("Quantity", null, new { @class = "form-control" })
                    <div id="ErrorMsgForQuantity" style="color:red"></div>
                </div>
            </div>
            <div class="col-md-3">
                <div class="form-group">
                    @Html.Label("Price")
                    @Html.TextBox("ItemPrice", null, new { @class = "form-control" })
                    <div id="ErrorMsgForItemPrice" style="color:red"></div>
                </div>
            </div>
            <div class="col-md-3">
                @Html.Label("Reason")
                @Html.TextArea("Reason", null, new { @class = "form-control" })
                <div id="ErrorMsgForReason" class="text-center" style="color:red"></div>
            </div>

        </div>

        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="form-group">

                    <input type="submit" id="btnAdd" value="Add" class="btn btn-success btn-block" />
                </div>
            </div>

        </div>

    </div>

</div>

<div class="panel panel-primary">
    <div class="panel-heading">
        Expense List
    </div>
    <div class="panel-body">
        <table class="table table-bordered table-condensed table-responsive table-hover ">
            <thead style="background-color:#80b107;color:white;">
                <tr>
                    <td>Item</td>
                    <td>Price</td>
                    <td>Quantity</td>
                    <td>Line Total</td>
                    <td>Reason</td>
                    <td>Action</td>
                </tr>
            </thead>
            <tbody id="ExpenseItemList"></tbody>
        </table>
    </div>

</div>


@using (Html.BeginForm("Create", "Expenses", FormMethod.Post, new { id = "form" }))
{
    @Html.AntiForgeryToken()
    <div class="panel panel-primary">
        <div class="panel-heading">
            Expense Information
        </div>
        <div class="panel-body">
            <h3 id="ErrorForTableRow" class="text-danger text-center"></h3>
            <div class="row">
                <div class="col-md-4">
                    <div class="">
                        <div class="form-group">
                            @Html.LabelFor(model => model.OutletId, "Outlet", htmlAttributes: new { })
                            <div>
                                @Html.DropDownList("OutletId", ViewBag.OutletId as SelectList, "---Select Outlet---", htmlAttributes: new { @class = "form-control" })
                                <div id="ErrorForOutlet" class="text-danger"></div>
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.EmployeeId, "Employee", htmlAttributes: new { })
                            <div>
                                @Html.DropDownList("EmployeeId", ViewBag.EmployeeId as SelectList, "---Select Employee---", htmlAttributes: new { @class = "form-control" })
                                <div id="ErrorForEmployee" class="text-danger"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-4">

                    <div class="form-group">
                        @Html.LabelFor(model => model.Date, htmlAttributes: new { })
                        <div>
                            @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control", placeholder = "Select a Date" } })
                            @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>
                <div class="col-md-4">
                    <div class="form-group">
                        @Html.LabelFor(model => model.Total, htmlAttributes: new { })
                        <div>
                            @Html.EditorFor(model => model.Total, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                            @Html.ValidationMessageFor(model => model.Total, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Due, htmlAttributes: new { })
                        <div>
                            @Html.EditorFor(model => model.Due, new { htmlAttributes = new { @class = "form-control", placeholder = "Due Amount" } })
                            @Html.ValidationMessageFor(model => model.Due, "", new { @class = "text-danger" })
                        </div>
                    </div>

                </div>
            </div>
            <div class="row">
                <div class="col-md-6 col-md-offset-3">
                    <div class="form-group">

                        <input type="submit" id="btnSubmit" value="Save" class="btn btn-success btn-block btn-lg" />
                    </div>
                </div>

            </div>
        </div>

    </div>
    <div id="bindValue"></div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/ProjectScript/Expense/Create_Expense.js"></script>
}

SuperShopManagementSystem/Views/Expenses/Details.cshtml
@model SuperShopManagementSystem.Models.ViewModel.ExpenseResultVM

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="col-md-12">
                    @Html.ActionLink("Download Pdf", "ExpenseReceiptPdf", new { id = Model.ExpenseNo }, new { @class = "btn btn-success" })
                    <div style="text-align:right">
                        <div class="h4">Extreme BD</div>
                        Extreme BD Super Shop
                        <div>Contact No. 01767111351</div>
                        <div>Sukrabad, Dhaka 1207</div>
                        <div>Bangladesh</div><br />
                    </div>
                </div>
                <div class="col-md-12 text-center">
                    <code class="h2" style="font-family:'Agency FB'">EXPENSE RESULT</code>
                </div>
                <div class="col-md-12">
                    <div style="height:2px;background-color:#00ffff"></div><br />
                </div>
                
                <div class="col-md-12">

                    <div class="col-md-6">
                        <strong>Expense No: </strong> @Html.DisplayFor(model => model.ExpenseNo)<br />
                        <strong>Expense Date: </strong> @Html.DisplayFor(model => model.Date)<br />

                    </div>
                    <div class="col-md-6">
                        <strong>Outlet: </strong> @Html.DisplayFor(model => model.Outlet)<br />
                        <strong>Employee: </strong> @Html.DisplayFor(model => model.Employee)<br />
                    </div>
                    <br />
                </div>

                <div class="col-md-12">
                    <br />
                </div>
                <div class="col-md-12">
                    <br />
                    <table class="table table-responsive table-condensed table-striped table-bordered">

                        <thead style="background-color:#99ad18;font-weight:bold">
                            <tr>
                                <td>SL</td>
                                <td>Item Name</td>
                                <td>Price</td>
                                <td>Quantity</td>
                                <td>Total Item Price</td>
                            </tr>
                        </thead>
                        <tbody>
                            @{int count = 0; }
                            @if (Model.ExpenseDetails != null)
                            {
                                foreach (var item in Model.ExpenseDetails)
                                {
                                    <tr>
                                        @{count++; }
                                        <td>@count</td>
                                        <td>@item.ExpenseItem.Name</td>
                                        <td>@item.Amount</td>
                                        <td>@item.Quantity</td>
                                        <td>@item.LineTotal</td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
                <div class="col-md-12">
                    <div class=" col-md-4 col-md-offset-8 pull-right">
                        <div style="height:2px;background-color:#00ffff"></div>
                        <strong>Total Price: </strong> @Html.DisplayFor(model => model.Total)<br />
                        <strong>Due: </strong> @Html.DisplayFor(model => model.Due)<br />
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

SuperShopManagementSystem/Views/Expenses/ExpenseResult.cshtml
@model SuperShopManagementSystem.Models.ViewModel.ExpenseResultVM

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Expense Result</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
    <br />
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="col-md-12">
                            <div style="text-align:right">
                                <div class="h4">Extreme BD</div>
                                Extreme BD Super Shop
                                <div>Contact No. 01767111351</div>
                                <div>Sukrabad, Dhaka 1207</div>
                                <div>Bangladesh</div><br />
                            </div>
                        </div>
                        <div class="col-md-12 text-center">
                            <code class="h2" style="font-family:'Agency FB'">EXPENSE RESULT</code>
                        </div>
                        <div class="col-md-12">
                            <div style="height:2px;background-color:#00ffff"></div>
                        </div>
                        <br />
                        <div class="col-xs-12">

                            <div class="col-xs-6">
                                <strong>Expense No: </strong> @Html.DisplayFor(model => model.ExpenseNo)<br />
                                <strong>Expense Date: </strong> @Html.DisplayFor(model => model.Date)<br />

                            </div>
                            <div class="col-xs-6">
                                <strong>Outlet: </strong> @Html.DisplayFor(model => model.Outlet)<br />
                                <strong>Employee: </strong> @Html.DisplayFor(model => model.Employee)<br />
                            </div>
                            <br />
                            <br />
                        </div>

                        <div class="col-xs-12">
                            <br />
                        </div>
                        <div class="col-xs-12">
                            <br />
                            <table class="table table-responsive table-condensed table-striped table-bordered">

                                <thead style="background-color:#99ad18;font-weight:bold">
                                    <tr>
                                        <td>SL</td>
                                        <td>Item Name</td>
                                        <td>Price</td>
                                        <td>Quantity</td>
                                        <td>Total Item Price</td>
                                    </tr>
                                </thead>
                                <tbody>
                                    @{int count = 0; }
                                    @if (Model.ExpenseDetails != null)
                                    {
                                        foreach (var item in Model.ExpenseDetails)
                                        {
                                            <tr>
                                                @{count++; }
                                                <td>@count</td>
                                                <td>@item.ExpenseItem.Name</td>
                                                <td>@item.Amount</td>
                                                <td>@item.Quantity</td>
                                                <td>@item.LineTotal</td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="col-xs-12">
                            <div class=" col-xs-4 col-md-offset-8 pull-right">
                                <div style="height:2px;background-color:#00ffff"></div>
                                <strong>Total Price: </strong> @Html.DisplayFor(model => model.Total)<br />
                                <strong>Due: </strong> @Html.DisplayFor(model => model.Due)<br />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

SuperShopManagementSystem/Views/Expenses/ShowAll.cshtml
@model IEnumerable<SuperShopManagementSystem.Models.Operation.Expense>

@{
    ViewBag.Title = "ShowAll";
}

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="text-center">All Purchase List</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12">
                        <table class="table table-bordered table-condensed table-striped table-responsive search-table ">
                            <thead>
                                <tr>
                                    <th>
                                        Outlet
                                    </th>
                                    <th>
                                        Employee
                                    </th>
                                    <th>
                                        Date
                                    </th>
                                    <th>
                                        Total
                                    </th>
                                    <th>
                                        Due
                                    </th>
               
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr id="DelRow_@item.Id">
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Outlet.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Employee.Name)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Date)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Total)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Due)
                                        </td>

                                        <td>
                                            @Html.ActionLink("Details", "Details", new { id = item.Id }, new { target = "_blank", @class = "btn btn-primary" })
                                            @Html.ActionLink("Download Pdf", "ExpenseReceiptPdf", new { id = item.Id }, new { target = "_blank", @class = "btn btn-success" })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>

                        @Html.Hidden("DeleteId")

                        <div id="myModal" class="modal fade" role="dialog">
                            <div class="modal-dialog">
                                Modal content
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal">&times;</button>

                                        <h2 class="modal-title">Confirm to Delete Item Category</h2>
                                    </div>
                                    <div class="modal-body">
                                        <h4>Are you sure to Delete this Item Category ???</h4>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                                        <input type="button" class="btn btn-danger" value="Confirm Delete" id="btnConfirmDelete" />
                                    </div>
                                </div>

                            </div>
                        </div>



                    </div>
                </div>

            </div>
        </div>
    </div>
</div>